language: ruby
rvm:
  - 2.2.2
services:
  - mongodb
env:
  - MONGOID_VERSION=4
before_script:
  - sleep 10
  - mongo kiwi_test --eval "db.addUser('travis', 'test');"
script: CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN bundle exec rake
